version: '3.9'

services:
  backend:
    build: .
    container_name: expenses_backend
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.expenses_bot.backend:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
      - ./credentials:/app/credentials:ro
      - ./user_session.session:/app/user_session.session:rw
    environment:
      - ENV=production
    env_file:
      - .env
    restart: unless-stopped

  bot:
    build: .
    container_name: expenses_bot
    command: poetry run python src/expenses_bot/bot.py
    volumes:
      - ./src:/app/src
      - ./credentials:/app/credentials:ro
      - ./user_session.session:/app/user_session.session:rw
    environment:
      - ENV=production
    env_file:
      - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel run expenses-backend
    volumes:
      - ~/.cloudflared:/etc/cloudflared:ro
    restart: unless-stopped